default_install_hook_types:
  - pre-commit
repos:
-   repo: https://github.com/timothycrosley/isort
    rev: 6.0.0
    hooks:
    - id: isort
      stages: [pre-commit, manual]
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    - id: flake8
      stages: [pre-commit, manual]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
    - id: mypy
-   repo: https://github.com/pycqa/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [--remove-all-unused-imports, --in-place]
        stages: [pre-commit, manual]
-   repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
    - id: black
      stages: [pre-commit, manual]